name: Generate TODO List

permissions:
  contents: write  # Allows the workflow to write to the repository
  
on:
  push:
    branches:
      - main  # Change this to your default branch if different
  pull_request:
    branches:
      - main  # Change this to your default branch if different
  workflow_dispatch:


jobs:
  generate-todo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the version you prefer

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found."

      - name: Generate TODO list
        run: python TODO_list_generator.py

      - name: Commit TODO list
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add TODO_list.md
          git commit -m "Update TODO_list.md" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
